import { build } from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Compiles the Svelte application into two strings.
 *
 * The page a webview shows cannot fetch anything. Its content security policy
 * allows this document's own inline style and its own nonced script and
 * nothing else — no CDN, no file next to it, no import at runtime. So the
 * application is compiled ahead of time and handed to the renderer as text, to
 * be pasted into the document it builds.
 *
 * Emitting a TypeScript module rather than writing the artefacts beside the
 * bundle keeps the existing arrangement: the page is a function of its inputs,
 * `tsc` is the only build step the other packages know about, and nothing has
 * to find a file on disk at render time.
 */
const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "src", "generated");

/**
 * The same components, compiled twice.
 *
 * A page has two lives. The host builds it as text — for a webview, for a file
 * `odin view` writes to disk, for an SVG nobody will ever click — and then, if
 * something is there to run it, it wakes up in a browser. Svelte compiles for
 * one or the other, so both are built and the document carries both: the
 * server rendering is what a reader sees before any script has run, and what
 * they keep if none ever does.
 *
 * That is the whole reason the SVG and HTML targets can share this code. A
 * static target simply never asks for the second half.
 */
async function compile(entry, generate) {
  return build({
    entryPoints: [join(HERE, "src", "app", entry)],
    bundle: true,
    // Nothing is written — the artefacts are captured below — but esbuild
    // still needs somewhere to name its outputs before it can split the
    // components' styles out of the JavaScript that imports them.
    outdir: join(HERE, "dist", "app"),
    write: false,
    format: generate === "server" ? "esm" : "iife",
    platform: generate === "server" ? "neutral" : "browser",
    target: "es2020",
    sourcemap: false,
    // The server bundle is read by Node, where nothing is downloading it and
    // a readable stack trace is worth more than the bytes.
    minify: generate === "client" && process.env.ODIN_DEV !== "1",
    logLevel: "warning",
    plugins: [
      esbuildSvelte({
        compilerOptions: {
          runes: true,
          generate,
          css: "external",
        },
      }),
    ],
  });
}

const browser = await compile("main.ts", "client");
const server = await compile("ssr.ts", "server");

/*
 * The sidebar, built the same way and built apart.
 *
 * Two documents with two lifetimes: the view beside the editor is rebuilt
 * whenever the change or the question behind its list changes, and the panel is
 * not. Bundling them together would put the whole canvas — cards, arrows,
 * comment threads — into a strip that draws none of it, and would parse it
 * again on every one of those rebuilds. What they do share, they share as
 * source: the components under `app/shared` are compiled into both.
 */
const sidebarBrowser = await compile("sidebar-main.ts", "client");
const sidebarServer = await compile("sidebar-ssr.ts", "server");

const script = text(browser, ".js");
// Styles come out of both builds identically — they are the components' own —
// so one is taken and the other discarded rather than shipped twice.
const styles = text(browser, ".css") || text(server, ".css");
const ssr = text(server, ".js");

const sidebarScript = text(sidebarBrowser, ".js");
const sidebarStyles = text(sidebarBrowser, ".css") || text(sidebarServer, ".css");
const sidebarSsr = text(sidebarServer, ".js");

await mkdir(OUT, { recursive: true });
await writeFile(
  join(OUT, "app.ts"),
  `/* Generated by packages/webview/build.mjs. Do not edit. */\n` +
    `\n` +
    `/** The compiled application, to be pasted into a nonced script tag. */\n` +
    `export const APP_SCRIPT: string = ${JSON.stringify(script)};\n` +
    `\n` +
    `/** Every component's styles, collected, for the document's own style tag. */\n` +
    `export const APP_STYLES: string = ${JSON.stringify(styles)};\n`,
  "utf8",
);

/*
 * The server rendering is emitted as source rather than as a string.
 *
 * It is called, not pasted, so it has to be a module Node can load — and the
 * only build step the other packages know about is `tsc`. Valid JavaScript is
 * valid TypeScript, so writing it into the source tree lets the ordinary build
 * carry it into `dist` with everything else. It is checked by the compiler
 * that produced it, not by this one.
 */
await writeFile(
  join(OUT, "ssr.ts"),
  `/* Generated by packages/webview/build.mjs. Do not edit. */\n` +
    `/* eslint-disable */\n` +
    `// @ts-nocheck\n` +
    ssr,
  "utf8",
);

await writeFile(
  join(OUT, "sidebar.ts"),
  `/* Generated by packages/webview/build.mjs. Do not edit. */\n` +
    `\n` +
    `/** The compiled sidebar, to be pasted into the view's script tag. */\n` +
    `export const SIDEBAR_SCRIPT: string = ${JSON.stringify(sidebarScript)};\n` +
    `\n` +
    `/** Its components' styles, collected, for the document's own style tag. */\n` +
    `export const SIDEBAR_STYLES: string = ${JSON.stringify(sidebarStyles)};\n`,
  "utf8",
);

await writeFile(
  join(OUT, "sidebar-ssr.ts"),
  `/* Generated by packages/webview/build.mjs. Do not edit. */\n` +
    `/* eslint-disable */\n` +
    `// @ts-nocheck\n` +
    sidebarSsr,
  "utf8",
);

console.log(
  `webview: ${(script.length / 1024).toFixed(0)}kb script, ` +
    `${(ssr.length / 1024).toFixed(0)}kb server, ` +
    `${(styles.length / 1024).toFixed(0)}kb styles`,
);
console.log(
  `sidebar: ${(sidebarScript.length / 1024).toFixed(0)}kb script, ` +
    `${(sidebarSsr.length / 1024).toFixed(0)}kb server, ` +
    `${(sidebarStyles.length / 1024).toFixed(0)}kb styles`,
);

/**
 * One output file's text.
 *
 * Serialised through `JSON.stringify` on the way into the generated module, so
 * a backtick or a `${` in a component's own source cannot end the template it
 * is pasted into — which is the failure mode the hand-written client script
 * had to be careful about by hand.
 */
function text(built, extension) {
  const file = built.outputFiles.find((f) => f.path.endsWith(extension));
  return file ? file.text : "";
}
